FROM ubuntu:22.04 as dev-img

ENV DEBIAN_FRONTEND=noninteractive

RUN apt -qq -y update \
	&& apt -qq -y upgrade \
	&& apt -qq -y install build-essential nasm \
	&& apt -qq -y install grub-common grub-pc-bin xorriso qemu-system-x86


FROM dev-img as usr-img

ARG USERNAME
ARG USR_UID
ARG USR_GID
	
RUN groupadd -o --gid $USR_GID $USERNAME \
	&& useradd -l -s /bin/bash --uid $USR_UID --gid $USR_GID -m $USERNAME \
	&& mkdir -p /etc/sudoers.d \
	&& echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
	&& chmod 0440 /etc/sudoers.d/$USERNAME

USER $USERNAME

WORKDIR /build
